/*
 * generated by Xtext 2.10.0
 */
package ssma.fml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FmlDslStandaloneSetup extends FmlDslStandaloneSetupGenerated {

	def static void doSetup() {
		new FmlDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
