/*
 * generated by Xtext 2.10.0
 */
package ssma.fml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FmlDslRuntimeModule extends AbstractFmlDslRuntimeModule {
}
