/*
 * generated by Xtext
 */
package ssma.fml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FmlDslStandaloneSetup extends FmlDslStandaloneSetupGenerated{

	public static void doSetup() {
		new FmlDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

