/*
 * generated by Xtext
 */
package ssma.fml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FmlDslRuntimeModule extends ssma.fml.AbstractFmlDslRuntimeModule {

}
