/*
 * generated by Xtext
 */
package ssma.sminv.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SminvDslUiModule extends ssma.sminv.ui.AbstractSminvDslUiModule {
	public SminvDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
