/*
 * generated by Xtext
 */
package ssma.sminv.scoping

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 *
 */
class SminvDslScopeProvider extends ssma.fml.scoping.FmlDslScopeProvider {

}
