/*
 * generated by Xtext 2.10.0
 */
package ssma.sminv


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SminvDslStandaloneSetup extends SminvDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SminvDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
