/*
 * generated by Xtext
 */
package ssma.sminv;

import ssma.fml.typing.TermTypeProvider;
import ssma.sminv.typing.TermTypeProviderWithVar;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SminvDslRuntimeModule extends ssma.sminv.AbstractSminvDslRuntimeModule {

    public Class<? extends TermTypeProvider> bindTermTypeProvider() {
        return TermTypeProviderWithVar.class;
    }

}
