/*
 * generated by Xtext
 */
package ssma.sminv;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SminvDslStandaloneSetup extends SminvDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SminvDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

