/*
 * generated by Xtext 2.10.0
 */
package ssma.sminv

import ssma.sminv.typing.TermTypeProviderWithVar
import ssma.fml.typing.TermTypeProvider


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SminvDslRuntimeModule extends AbstractSminvDslRuntimeModule {

    def Class<? extends TermTypeProvider> bindTermTypeProvider() {
        TermTypeProviderWithVar
    }

}
