/*
 * generated by Xtext
 */
package ssma.frontend.pn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PnDslUiModule extends ssma.frontend.pn.ui.AbstractPnDslUiModule {
	public PnDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
