/*
 * generated by Xtext
 */
package ssma.frontend.pn.ui.contentassist

import ssma.frontend.pn.ui.contentassist.AbstractPnDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PnDslProposalProvider extends AbstractPnDslProposalProvider {
}
