/*
 * generated by Xtext
 */
package ssma.fml.ui.contentassist

import ssma.fml.ui.contentassist.AbstractFmlDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class FmlDslProposalProvider extends AbstractFmlDslProposalProvider {
}
