/*
 * generated by Xtext
 */
package ssma.fml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FmlDslUiModule extends ssma.fml.ui.AbstractFmlDslUiModule {
	public FmlDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
