/*
 * generated by Xtext
 */
package ssma.frontend.pn;

import ssma.fml.typing.TermTypeProvider;
import ssma.frontend.pn.typing.TermTypeProviderForPlaceFml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PnDslRuntimeModule extends ssma.frontend.pn.AbstractPnDslRuntimeModule {

    public Class<? extends TermTypeProvider> bindTermTypeProvider() {
        return TermTypeProviderForPlaceFml.class;
    }

}
