/*
 * generated by Xtext
 */
package ssma.frontend.pn;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PnDslStandaloneSetup extends PnDslStandaloneSetupGenerated{

	public static void doSetup() {
		new PnDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

