/*
 * generated by Xtext
 */
package ssma.sminv.ui.contentassist

import ssma.sminv.ui.contentassist.AbstractSminvDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SminvDslProposalProvider extends AbstractSminvDslProposalProvider {
}
